services:
  db:
    image: postgres:16
    container_name: planner_db
    restart: always
    environment:
      POSTGRES_DB: planner_db
      POSTGRES_USER: planner_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: planner_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg://planner_user:supersecretpassword@db:5432/planner_db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: planner_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"   # host:container

volumes:
  db_data:
